# Generated by Django 4.2.4 on 2023-08-10 11:08

import adminpanel.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        verbose_name="Name of the zone/location",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="Name of the plant"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        default=adminpanel.models.Zone.get_default_pk,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="plants_under",
                        to="adminpanel.zone",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cases",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(99),
                            django.core.validators.MaxValueValidator(1000000000),
                        ],
                        verbose_name="Amount of particular case (in mL)",
                    ),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MaxValueValidator(1000000000)
                        ],
                        verbose_name="No. of units of given case",
                    ),
                ),
                (
                    "for_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_cases",
                        to="adminpanel.plant",
                        verbose_name="Case for plant",
                    ),
                ),
            ],
        ),
    ]
