# Generated by Django 4.2.4 on 2023-08-10 12:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cases",
            new_name="Case",
        ),
    ]
