# Generated by Django 4.2.4 on 2023-08-11 09:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0002_rename_cases_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="case",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
