# Generated by Django 4.2.4 on 2023-08-20 12:53

import adminpanel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("adminpanel", "0003_case_date_created_case_last_updated"),
        ("authorizer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="assigned_plant",
            field=models.ForeignKey(
                default=adminpanel.models.Plant.get_default_pk,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="supervisor_profile",
                to="adminpanel.plant",
            ),
        ),
    ]
